// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/ports/checksum_hasher.go (interfaces: ChecksumHasher)
//
// Generated by this command:
//
//	mockgen -package ports internal/domain/ports/checksum_hasher.go ChecksumHasher
//

// Package ports is a generated GoMock package.
package ports

import (
	io "io"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockChecksumHasher is a mock of ChecksumHasher interface.
type MockChecksumHasher struct {
	ctrl     *gomock.Controller
	recorder *MockChecksumHasherMockRecorder
	isgomock struct{}
}

// MockChecksumHasherMockRecorder is the mock recorder for MockChecksumHasher.
type MockChecksumHasherMockRecorder struct {
	mock *MockChecksumHasher
}

// NewMockChecksumHasher creates a new mock instance.
func NewMockChecksumHasher(ctrl *gomock.Controller) *MockChecksumHasher {
	mock := &MockChecksumHasher{ctrl: ctrl}
	mock.recorder = &MockChecksumHasherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChecksumHasher) EXPECT() *MockChecksumHasherMockRecorder {
	return m.recorder
}

// AsWriter mocks base method.
func (m *MockChecksumHasher) AsWriter() io.Writer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AsWriter")
	ret0, _ := ret[0].(io.Writer)
	return ret0
}

// AsWriter indicates an expected call of AsWriter.
func (mr *MockChecksumHasherMockRecorder) AsWriter() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AsWriter", reflect.TypeOf((*MockChecksumHasher)(nil).AsWriter))
}

// CompareFromReader mocks base method.
func (m *MockChecksumHasher) CompareFromReader(reader io.Reader, hashedValue string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompareFromReader", reader, hashedValue)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CompareFromReader indicates an expected call of CompareFromReader.
func (mr *MockChecksumHasherMockRecorder) CompareFromReader(reader, hashedValue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompareFromReader", reflect.TypeOf((*MockChecksumHasher)(nil).CompareFromReader), reader, hashedValue)
}

// ComputeFromReaderToBase64 mocks base method.
func (m *MockChecksumHasher) ComputeFromReaderToBase64(reader io.Reader) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ComputeFromReaderToBase64", reader)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ComputeFromReaderToBase64 indicates an expected call of ComputeFromReaderToBase64.
func (mr *MockChecksumHasherMockRecorder) ComputeFromReaderToBase64(reader any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ComputeFromReaderToBase64", reflect.TypeOf((*MockChecksumHasher)(nil).ComputeFromReaderToBase64), reader)
}

// ComputeToBase64 mocks base method.
func (m *MockChecksumHasher) ComputeToBase64() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ComputeToBase64")
	ret0, _ := ret[0].(string)
	return ret0
}

// ComputeToBase64 indicates an expected call of ComputeToBase64.
func (mr *MockChecksumHasherMockRecorder) ComputeToBase64() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ComputeToBase64", reflect.TypeOf((*MockChecksumHasher)(nil).ComputeToBase64))
}

// Reset mocks base method.
func (m *MockChecksumHasher) Reset() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Reset")
}

// Reset indicates an expected call of Reset.
func (mr *MockChecksumHasherMockRecorder) Reset() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reset", reflect.TypeOf((*MockChecksumHasher)(nil).Reset))
}
