// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/ports/storage.go (interfaces: ObjectStorage)
//
// Generated by this command:
//
//	mockgen -package ports internal/domain/ports/storage.go ObjectStorage
//

// Package ports is a generated GoMock package.
package ports

import (
	context "context"
	io "io"
	reflect "reflect"

	entities "github.com/dinno7/artinux/internal/domain/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockObjectStorage is a mock of ObjectStorage interface.
type MockObjectStorage struct {
	ctrl     *gomock.Controller
	recorder *MockObjectStorageMockRecorder
	isgomock struct{}
}

// MockObjectStorageMockRecorder is the mock recorder for MockObjectStorage.
type MockObjectStorageMockRecorder struct {
	mock *MockObjectStorage
}

// NewMockObjectStorage creates a new mock instance.
func NewMockObjectStorage(ctrl *gomock.Controller) *MockObjectStorage {
	mock := &MockObjectStorage{ctrl: ctrl}
	mock.recorder = &MockObjectStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObjectStorage) EXPECT() *MockObjectStorageMockRecorder {
	return m.recorder
}

// ClearBucket mocks base method.
func (m *MockObjectStorage) ClearBucket(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearBucket", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearBucket indicates an expected call of ClearBucket.
func (mr *MockObjectStorageMockRecorder) ClearBucket(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearBucket", reflect.TypeOf((*MockObjectStorage)(nil).ClearBucket), ctx)
}

// CreateBucket mocks base method.
func (m *MockObjectStorage) CreateBucket(ctx context.Context, bucketName, region string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBucket", ctx, bucketName, region)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBucket indicates an expected call of CreateBucket.
func (mr *MockObjectStorageMockRecorder) CreateBucket(ctx, bucketName, region any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBucket", reflect.TypeOf((*MockObjectStorage)(nil).CreateBucket), ctx, bucketName, region)
}

// DeleteBatch mocks base method.
func (m *MockObjectStorage) DeleteBatch(ctx context.Context, objectKeys []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBatch", ctx, objectKeys)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBatch indicates an expected call of DeleteBatch.
func (mr *MockObjectStorageMockRecorder) DeleteBatch(ctx, objectKeys any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBatch", reflect.TypeOf((*MockObjectStorage)(nil).DeleteBatch), ctx, objectKeys)
}

// DeleteObject mocks base method.
func (m *MockObjectStorage) DeleteObject(ctx context.Context, objectKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteObject", ctx, objectKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteObject indicates an expected call of DeleteObject.
func (mr *MockObjectStorageMockRecorder) DeleteObject(ctx, objectKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteObject", reflect.TypeOf((*MockObjectStorage)(nil).DeleteObject), ctx, objectKey)
}

// Download mocks base method.
func (m *MockObjectStorage) Download(ctx context.Context, objectKey string) (io.ReadSeekCloser, *entities.Artifact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Download", ctx, objectKey)
	ret0, _ := ret[0].(io.ReadSeekCloser)
	ret1, _ := ret[1].(*entities.Artifact)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Download indicates an expected call of Download.
func (mr *MockObjectStorageMockRecorder) Download(ctx, objectKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Download", reflect.TypeOf((*MockObjectStorage)(nil).Download), ctx, objectKey)
}

// ListObjects mocks base method.
func (m *MockObjectStorage) ListObjects(ctx context.Context, prefix string, limit int) ([]*entities.Artifact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListObjects", ctx, prefix, limit)
	ret0, _ := ret[0].([]*entities.Artifact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListObjects indicates an expected call of ListObjects.
func (mr *MockObjectStorageMockRecorder) ListObjects(ctx, prefix, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListObjects", reflect.TypeOf((*MockObjectStorage)(nil).ListObjects), ctx, prefix, limit)
}

// Ping mocks base method.
func (m *MockObjectStorage) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockObjectStorageMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockObjectStorage)(nil).Ping), ctx)
}

// Upload mocks base method.
func (m *MockObjectStorage) Upload(ctx context.Context, reader io.Reader, artifact *entities.Artifact) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upload", ctx, reader, artifact)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upload indicates an expected call of Upload.
func (mr *MockObjectStorageMockRecorder) Upload(ctx, reader, artifact any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockObjectStorage)(nil).Upload), ctx, reader, artifact)
}
